import { useEffect, useRef, useState } from 'react';
import { gsap, useGSAP, prefersReducedMotion } from '../lib/gsapSetup';
import { Icon } from './Icons';
import { api } from '../api';
import { NotionDriftPanel } from './NotionDriftPanel';
import type { AuditEvent } from '../types';

/** Icon + wording carry the meaning; colour is only ever a secondary cue. */
const ACTION_META: Record<string, { label: string; Icon: (p: { className?: string }) => JSX.Element }> = {
  create: { label: 'Added', Icon: Icon.Plus },
  update: { label: 'Edited', Icon: Icon.Arrow },
  delete: { label: 'Deleted', Icon: Icon.Trash },
  'cv-request': { label: 'CV queued', Icon: Icon.Sparkle },
  'cv-generated': { label: 'CV generated', Icon: Icon.Check },
  'review-request': { label: 'Review queued', Icon: Icon.Search },
  'cv-reviewed': { label: 'CV reviewed', Icon: Icon.Shield },
  'docs-verified': { label: 'Docs verified', Icon: Icon.Shield },
  'doc-generated': { label: 'Document generated', Icon: Icon.Check },
  'priority-set': { label: 'Priority set', Icon: Icon.Zap },
  'evidence-refined': { label: 'Evidence refined', Icon: Icon.Shield },
  'war-room-drafted': { label: 'War room drafted', Icon: Icon.Chat },
  'rejection-analysed': { label: 'Rejection analysed', Icon: Icon.Close },
  'outreach-create': { label: 'Outreach added', Icon: Icon.Building },
  'outreach-update': { label: 'Outreach edited', Icon: Icon.Arrow },
  'outreach-delete': { label: 'Outreach removed', Icon: Icon.Trash },
  'outreach-email-request': { label: 'Email queued', Icon: Icon.Sparkle },
  'outreach-email-sent': { label: 'Email sent', Icon: Icon.Paperplane },
};

function when(at: number) {
  const d = new Date(at);
  return d.toLocaleString(undefined, {
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/** The raw event log — Learning Loop analysis used to live above this list
 *  under the same "Activity" heading, which buried the feature Kironraj
 *  actually relies on inside what reads as a changelog. It now has its own
 *  tab on the Insights page; this is left as what it actually is, a
 *  debugging surface over `audit-log.jsonl`. */
export function AuditView() {
  const [events, setEvents] = useState<AuditEvent[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const listRef = useRef<HTMLDivElement>(null);

  useGSAP(
    () => {
      const reduce = prefersReducedMotion();
      gsap.from('.audit-row', {
        opacity: 0,
        duration: reduce ? 0 : 0.25,
        delay: reduce ? 0 : (i: number) => Math.min(i * 0.015, 0.3),
      });
    },
    { scope: listRef, dependencies: [events] }
  );

  useEffect(() => {
    let alive = true;
    api
      .auditLog()
      .then((e) => alive && setEvents(e))
      .catch((err) => alive && setError(err instanceof Error ? err.message : String(err)));
    return () => {
      alive = false;
    };
  }, []);

  if (error) {
    return (
      <>
        <NotionDriftPanel />
        <div className="rounded-2xl border border-rose/30 bg-panel p-5 text-meta text-rose">
          Couldn't load the audit log — {error}
        </div>
      </>
    );
  }

  if (!events) {
    return (
      <>
        <NotionDriftPanel />
        <div className="py-16 text-center text-meta text-ink-faint">Loading…</div>
      </>
    );
  }

  if (events.length === 0) {
    return (
      <>
        <NotionDriftPanel />
        <div className="panel-empty px-6 py-16 text-center">
          <Icon.Clock className="mx-auto mb-3 h-8 w-8 text-ink-faint" />
          <p className="text-subhead text-ink">Nothing logged yet</p>
          <p className="mt-1.5 text-meta text-ink-soft">
            Edits made in the app and documents generated by Claude both land here.
          </p>
        </div>
      </>
    );
  }

  return (
    <>
      <NotionDriftPanel />
      <div ref={listRef} className="overflow-hidden rounded-2xl border border-line bg-panel">
      {events.map((e, i) => {
        const meta = ACTION_META[e.action] ?? { label: e.action, Icon: Icon.Arrow };
        const byClaude = e.actor === 'claude';
        return (
          <div
            key={`${e.at}-${i}`}
            className="audit-row flex items-start gap-3 border-b border-line-soft px-5 py-3.5 last:border-b-0"
          >
            <span className="mt-0.5 text-ink-faint">
              <meta.Icon className="h-3.5 w-3.5" />
            </span>
            <div className="min-w-0 flex-1">
              <p className="text-meta text-ink">
                {meta.label}
                {e.detail ? <span className="text-ink-soft"> · {e.detail}</span> : null}
              </p>
              <p className="mt-0.5 text-micro text-ink-faint">
                {when(e.at)} · {byClaude ? 'by Claude' : 'by you'}
              </p>
            </div>
          </div>
        );
      })}
      </div>
    </>
  );
}
